### ISSUE TITLE
Rename fbn notes failed 

### ISSUE THREAD

**Issue by TrevorLink** [Creator-SN/Fabulous#1]
**Describe the bug**
When using notes module and after creating a new fbn file , it seems that we cannot rename the fbn file

**To Reproduce**
1. Go to notes module
2. Click to create a new fbn file
3. Right click and chose `rename file`
4. Open the console dev tools 
5. See error message

**Expected behavior**
Cannot rename the fbn and the console log with error
```
vue.esm.js:3736 TypeError: i.replace is not a function
    at a.nameJudge (pdfItem.vue?677b:593:1)
    at a.rename (pdfItem.vue?677b:649:1)
    at click (noteLayer.vue?f0f3:1:2398)
    at br (vue.esm.js:3704:30)
    at a.n (vue.esm.js:1524:20)
    at br (vue.esm.js:3704:30)
    at Cn.e.$emit (vue.esm.js:2793:17)
    at a.onClick (powereditor.umd.min.js:13:84553)
    at br (vue.esm.js:3704:30)
    at HTMLDivElement.n (vue.esm.js:1524:20)
```

**Platform**
Windows 11、Fabulous version :0.1.7

**Comment by aleversn** [comment]
this issue has been fixed in version v0.1.8
